### PR TITLE
Enabled download of includes over HTTP (#605)

### LINKED ISSUE #605: Support git+http
**Is your feature request related to a problem? Please describe.**
I have a private gitlab-instance that has no ssh-access enabled. I have to clone/push/etc via https.

When using includes in my `gitlab-ci.yaml`, gitlab-ci-local tries to download these includes. The function `downloadIncludeProjectFile` uses `git archive` under the hood which does not work with https but only with ssh.

**Describe the solution you'd like**
I'd like to use includes with my instance that has no ssh enabled.

**Describe alternatives you've considered**
- 

**Additional context**
I thought about doing it with curl or wget via the gitlab API like this:

```
    static async downloadIncludeProjectFile (cwd: string, stateDir: string, project: string, ref: string, file: string, gitData: GitData, fetchIncludes: boolean): Promise<void> {
        const remote = gitData.remote;
        const normalizedFile = file.replace(/^\/+/, "");
        try {
            const target = `${stateDir}/includes/${remote.host}/${project}/${ref}/`;
            if (await fs.pathExists(`${cwd}/${target}/${normalizedFile}`) && !fetchIncludes) return;
            await fs.mkdirp(`${cwd}/${target}`);
            await Utils.bash(`git archive --remote=ssh://git@${remote.host}:${remote.port}/${project}.git ${ref} ${normalizedFile} | tar -f - -xC ${target}`, cwd);
        } catch (e) {
            try {
              const target = `${stateDir}/includes/${remote.host}/${project}/${ref}/`;
              if (await fs.pathExists(`${cwd}/${target}/${normalizedFile}`) && !fetchIncludes) return;
              await fs.mkdirp(`${cwd}/${target}`);
              await Utils.bash(`curl --header "Private-Token: ${token}" -O ${target}/${normalizedFile} https://${fomain}/api/v4/projects/${project}/repository/files/${normalizedFile}?ref=${ref}`, cwd);
            } catch (e) {
            throw new ExitError(`Project include could not be fetched { project: ${project}, ref: ${ref}, file: ${normalizedFile} }`)
;
          }
        }
    }
```

Or maybe with axios? However I'm not proficient with javascript to include a working solution.

### PR DESCRIPTION
**Pull request by docdnp**
* Added option --git-over-http (default: false)
* When active: Include-Parser uses git spare-checkout instead of git archive

closes #605

### CODE REVIEW

**Comment by firecow** [comment]
@docdnp Isn't it possible to "auto-detect" that the checkout is a "http" checkout?

That way we can avoid having a specific cli option that http users needs to remember.

**Comment by docdnp** [comment]
> @docdnp Isn't it possible to "auto-detect" that the checkout is a "http" checkout?
> 
> That way we can avoid having a specific cli option that http users needs to remember.

Well, yes.. could do it via: `git config --get remote.origin.url`

**Comment by docdnp** [comment]
@firecow In case you insist on the removal of the CLI option I'll  do it. I don't see what reason might break the autodetection. The more I think about it, it should be better removed. Just let me know.

**Comment by firecow** [comment]
@docdnp Let's auto detect it.

I'll check out the jest tests.

I think we might have a broken test, sometimes :+1:

**Comment by firecow** [comment]
In `git-data.ts` the "remote" is already parsed.

I suggest you edit the regexp to this

```
(?<schema>https|git|http:)(?::\/\/|@)(?<host>[^:/]*)(:(?<port>\d+)\/|:|\/)(?<group>.*)\/(?<project>[^ .]+)(?:\.git)?.*
```

And add a 
```
this.remote.schema = gitRemoteMatch.groups.schema;
```

You will then be able to use the schema as your condition instead of `git config --get remote.origin.url`

The reason your jest test is failing is because you don't have a "bash spy" setup in the `include-invalid-project-file-ref` test-case.

**Comment by docdnp** [comment]
OK. Sounds good. I'll check it out. I've been already playing around with `include-invalid-project-file-ref` but stumbled over the attempt of the test setup to make some calls to your (firecow) gitlab repository.

Thanks for the hint. I'll come back in case of any further questions or obstacles.

**Comment by docdnp** [comment]
I've added `<protocol>` instead of `<schema>` in `git-data.ts` and changed the regular expression to 
  
   `/(?:.*?)\s+(?<protocol>.*?)(?::\/\/|@)(?<host>[^:\/]*)(:(?<port>\d+)\/|:|\/)(?<group>.*)\/(?<project>[^ .]+)(?:\.git)?.*/`

Double-checked the regexp in perl

```perl
#!/usr/bin/perl -n
# file: regexp.pl

    /   (?:.*?)\s+
        (?<protocol>.*?)
        (?::\/\/|@)
        (?<host>[^:\/]*)
        (:(?<port>\d+)\/|:|\/)
        (?<group>.*)
        \/
        (?<project>[^ .]+)
        (?:\.git)?.*
    /x && print   "Protocol: ", $+{protocol},  "\nHost    : ", $+{host}, 
                "\nGroup   : ", $+{group},     "\nProject : ", $+{project}, "\n"
```
using  `git remote -v | head -1 | regexp.pl`. I was a bit surprised that `[^:/]`  works in TS. Perl complains, and needs `[^:\/]` in line 7 after the `host`. I think it could be even simplified when used against `git config --get remote.origin.url` instead of `git remote -v`, like this:

```perl
#!/usr/bin/perl -n
# file: regexp.pl

    /   (?<protocol>.*?)
        (?::\/\/|@)
        (?<host>[^:\/]*)
        (:(?<port>\d+)\/|:|\/)
        (?<group>.*)
        \/
        (?<project>[^ .]+)
        (?:\.git)?
    /xx && print   "Protocol: ", $+{protocol},  "\nHost    : ", $+{host}, 
                "\nGroup   : ", $+{group},     "\nProject : ", $+{project}, "\n"
```
Don't know whether `gitRemoteMatch` matches exactly, but wouldn't assume it.

Nevertheless do I doubt that the errors won't appear now anymore, but who knows how surprised I will be if you're right.
Actually I wish you're right, even if I don't understand it. ;-)

**Comment by firecow** [comment]
Use the regex i pasted

**Comment by docdnp** [comment]
OK. Done. But had to correct your suggestion, as it didn't catch pure 'http://' origins. Here a way to test it out... 

Test data is:
```shell
# file: git.remote.out
origin	https://github.com/docdnp/gitlab-ci-local.git (fetch)
origin	git@github.com:docdnp/gitlab-ci-local.git (fetch)
origin	http://github.com/docdnp/gitlab-ci-local.git (fetch)
```

Script is:
```perl
#!/usr/bin/perl -n
# file: regexp.pl

$reschema = $ENV{use_regexp_firecow} == 1 ? qr((?<schema>https|git|http:)) : qr((?<schema>git|https?));

/   $reschema
    (?::\/\/|@)
    (?<host>[^:\/]*)
    (:(?<port>\d+)\/|:|\/)
    (?<group>.*)
    \/
    (?<project>[^ .]+)
    (?:\.git)?
/xx && print    "Schema : '", $+{schema},   "'\nHost   : '", $+{host}, 
                "'\nGroup  : '", $+{group},    "'\nProject: '", $+{project}, "'\n",
```
Test is:
```python
docdnp:gitlab-ci-local $ cat git.remote.out | use_regexp_firecow=1 ./regexp.pl
Schema : 'https'
Host   : 'github.com'
Group  : 'docdnp'
Project: 'gitlab-ci-local'
Schema : 'git'
Host   : 'github.com'
Group  : 'docdnp'
Project: 'gitlab-ci-local'
docdnp:gitlab-ci-local $ cat git.remote.out | use_regexp_firecow=0 ./regexp.pl
Schema : 'https'
Host   : 'github.com'
Group  : 'docdnp'
Project: 'gitlab-ci-local'
Schema : 'git'
Host   : 'github.com'
Group  : 'docdnp'
Project: 'gitlab-ci-local'
Schema : 'http'
Host   : 'github.com'
Group  : 'docdnp'
Project: 'gitlab-ci-local'
```
As far as I see in the latest [test report](https://github.com/firecow/gitlab-ci-local/actions/runs/5866272870/job/15905072455) my assumption regarding the reason of the test failures was correct, as the error logs don't show anything related to the regexp or my changes.
```shell
Summary of all failing tests
 FAIL  tests/test-cases/include-invalid-project-file-ref/integration.include-invalid-project-ref-file.test.ts
  ● include-invalid-project-file-ref
  [...]
      Project include could not be fetched { project: firecow/gitlab-ci-local-includes, ref: HEAD, file: .gitlab-modue.yml }
    - Error: git archive | tar -f - -xC failed horribly
    -   this is a core error
    -   read it carefully
    + Error: Command failed with exit code 2: git archive --remote=ssh://git@gitlab.com:22/firecow/gitlab-ci-local-includes.git HEAD .gitlab-modue.yml | tar -f - -xC .gitlab-ci-local/includes/gitlab.com/firecow/gitlab-ci-local-includes/HEAD
    + Host key verification failed.
    
    + fatal: the remote end hung up unexpectedly
    + tar: This does not look like a tar archive
    + tar: Exiting with failure status due to previous errors
```
I assume that their is a basic problem related to credentials or so:
```
    + Host key verification failed.
    + fatal: the remote end hung up unexpectedly
```
Now I'm trying to reproduce it with my own gitlab repository. Or is there any other way to test this stuff locally to decrease the feedback cycle?

**Comment by docdnp** [comment]
Yeah. That's the way I'm doing local tests. Actually I see other tests failing than in the pipeline. That's a bit confusing as I don't know whether it depends on the changes I made or on other issues or whether the tests are a bit fragile.

You opened a pull request on the same issue? Why?

**Comment by firecow** [comment]
Just to test whats going on

**Comment by docdnp** [comment]
Now I'm quiet sure, that we're suffering of brittle tests. Made an analysis on 10 consecutive test runs. My personal opinion is at the end of this comment. Here the results in short:
```python
Testrun 01:     Test Suites: 3 failed, 94 passed, 97 total      Tests:       4 failed, 212 passed, 216 total
Testrun 02:     Test Suites: 3 failed, 94 passed, 97 total      Tests:       4 failed, 212 passed, 216 total
Testrun 03:     Test Suites: 1 failed, 96 passed, 97 total      Tests:       2 failed, 214 passed, 216 total
Testrun 04:     Test Suites: 5 failed, 92 passed, 97 total      Tests:       5 failed, 211 passed, 216 total
Testrun 05:     Test Suites: 3 failed, 94 passed, 97 total      Tests:       4 failed, 212 passed, 216 total
Testrun 06:     Test Suites: 4 failed, 93 passed, 97 total      Tests:       4 failed, 212 passed, 216 total
Testrun 07:     Test Suites: 2 failed, 95 passed, 97 total      Tests:       2 failed, 214 passed, 216 total
Testrun 08:     Test Suites: 4 failed, 93 passed, 97 total      Tests:       5 failed, 211 passed, 216 total
Testrun 09:     Test Suites: 2 failed, 95 passed, 97 total      Tests:       3 failed, 213 passed, 216 total
Testrun 10:     Test Suites: 3 failed, 94 passed, 97 total      Tests:       3 failed, 213 passed, 216 total
```
I wanted also to know in how many test runs a failing test occured:
* File: `tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts`
  - Testruns:   04  05
* File: `tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts`
  - Testruns:   01  02  04  05  06  08  09  10
* File: `tests/test-cases/network-alias-build/integration.network-alias-build.test.ts`
  - Testruns:   01  02  03  04  05  06  07  08  09  10
* File: `tests/test-cases/artifacts-with-cache/integration.artifacts-with-cache.test.ts`
  - Testruns:   01  02  04  06  08
* File: `tests/test-cases/cache-docker/integration.cache-docker.test.ts`
  - Testruns:   04  06  07  08  10

Here some more details on the failing tests involved:
```python
Testrun 01:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.035 s)
 FAIL  tests/test-cases/artifacts-with-cache/integration.artifacts-with-cache.test.ts (5.261 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.885 s)
Test Suites: 3 failed, 94 passed, 97 total
Tests:       4 failed, 212 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        176.629 s

Testrun 02:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.228 s)
 FAIL  tests/test-cases/artifacts-with-cache/integration.artifacts-with-cache.test.ts (5.24 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.964 s)
Test Suites: 3 failed, 94 passed, 97 total
Tests:       4 failed, 212 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        185.873 s

Testrun 03:
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (12.336 s)
Test Suites: 1 failed, 96 passed, 97 total
Tests:       2 failed, 214 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        176.578 s

Testrun 04:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.201 s)
 FAIL  tests/test-cases/artifacts-with-cache/integration.artifacts-with-cache.test.ts (5.263 s)
 FAIL  tests/test-cases/cache-docker/integration.cache-docker.test.ts (5.247 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.853 s)
 FAIL  tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts
Test Suites: 5 failed, 92 passed, 97 total
Tests:       5 failed, 211 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        187.093 s

Testrun 05:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.038 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.84 s)
 FAIL  tests/test-cases/parallel-matrix/integration.parallel-matrix.test.ts
Test Suites: 3 failed, 94 passed, 97 total
Tests:       4 failed, 212 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        184.324 s

Testrun 06:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.26 s)
 FAIL  tests/test-cases/artifacts-with-cache/integration.artifacts-with-cache.test.ts (5.324 s)
 FAIL  tests/test-cases/cache-docker/integration.cache-docker.test.ts (5.247 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.915 s)
Test Suites: 4 failed, 93 passed, 97 total
Tests:       4 failed, 212 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        180.757 s

Testrun 07:
 FAIL  tests/test-cases/cache-docker/integration.cache-docker.test.ts (5.222 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.92 s)
Test Suites: 2 failed, 95 passed, 97 total
Tests:       2 failed, 214 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        179.786 s

Testrun 08:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.185 s)
 FAIL  tests/test-cases/artifacts-with-cache/integration.artifacts-with-cache.test.ts (5.222 s)
 FAIL  tests/test-cases/cache-docker/integration.cache-docker.test.ts (5.225 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (12.01 s)
Test Suites: 4 failed, 93 passed, 97 total
Tests:       5 failed, 211 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        187.418 s

Testrun 09:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.123 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.999 s)
Test Suites: 2 failed, 95 passed, 97 total
Tests:       3 failed, 213 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        178.611 s

Testrun 10:
 FAIL  tests/test-cases/artifacts-reports-dotenv/integration.artifacts-reports-dotenv.test.ts (6.105 s)
 FAIL  tests/test-cases/cache-docker/integration.cache-docker.test.ts (5.177 s)
 FAIL  tests/test-cases/network-alias-build/integration.network-alias-build.test.ts (11.316 s)
Test Suites: 3 failed, 94 passed, 97 total
Tests:       3 failed, 213 passed, 216 total
Snapshots:   4 passed, 4 total
Time:        173.606 s
```
Do you know what's going on or have any hint, where I maybe don't test correctly? I'm always cautios regarding critique on when I begin to work in foreign codebases and assume in the first place, that I'm the one who maybe doesn't know exactly what he's doing.

But, to be honest, I don't believe anymore in the code changes that enable sparse checkouts are in any way connected to the failing tests. What is your opinion on that? I would suggest the following:
* Let us finish the pull request
* Let us later on figure out what the heck is so fragile with those tests

Are you OK with that?

**Comment by firecow** [comment]
I'm quiet sure we have a brittle test in master.

I've only been able to get the parallel matrix test to fail occasionally though.

Try using these jest cli options

https://jestjs.io/docs/cli#--runinband
https://jestjs.io/docs/cli#--testtimeoutnumber
https://jestjs.io/docs/cli#--maxconcurrencynum

**Comment by firecow** [comment]
parallel matrix concurrent have been disabled fixing the flapping test case
https://github.com/firecow/gitlab-ci-local/actions/runs/5875837064

**Comment by docdnp** [comment]
OK. Testing without concurrency and a longer timeout works stable. You mean I should remove tsnode from package.json? And are you sure about reverting the test case? Actually the changes made the test run through.

I'll do the changes a bit later this evening. Just give me a short answer.

**Comment by firecow** [comment]
Yeah, the test file changes are irrelevant...

Just let ts-node stay if you want, just thought devs installed that globally.

**Comment by docdnp** [comment]
Did what you said. The test [integration.include-invalid-project-ref-file.test.ts](https://github.com/firecow/gitlab-ci-local/actions/runs/5888759940/job/15973552333?pr=958) fails again... as I assumed.

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/960/files Have a look at this.

**Comment by docdnp** [comment]
Well, thank you.. I think I've got it running now. Actually it was just a damn "/" missing in the "target" path. "tar" wasn't happy about this and thus the test failed. My fault. :-/

**Review by firecow — APPROVED** [review]
Looks great. Good job :+1:

**Comment by docdnp** [comment]
Great. 👍 Thank you for the hints to the right direction.

**Comment by firecow** [comment]
No problem at all :+1:

**Comment by codespearhead** [comment]
Should this be removed then?

https://github.com/firecow/gitlab-ci-local/blob/cec7ccdf255e8b73fad1c4139271d020a3bcdde9/README.md?plain=1#L210-L212

**Pull request merged**
