### PR TITLE
feat: Define inputs for configuration added with include

### PR DESCRIPTION
**Pull request by ANGkeith**
[Define inputs for configuration added with include
](https://docs.gitlab.com/ee/ci/yaml/inputs.html)
unimplemented:
- https://docs.gitlab.com/ee/ci/yaml/index.html#specinputsregex
- https://docs.gitlab.com/ee/ci/yaml/inputs.html#specify-functions-to-manipulate-input-values

Closes https://github.com/firecow/gitlab-ci-local/issues/940

### CODE REVIEW

**Comment by firecow** [comment]
Good job @ANGkeith 

Fix the yaml warnings https://github.com/firecow/gitlab-ci-local/actions/runs/8039438112/job/21968747743?pr=1115, and we are good to go :+1:

**Review by firecow — APPROVED** [review]
Very nice :smile:

**Comment by firecow** [comment]
@ANGkeith 

```
stages: [format, build, test]

include:
  - component: example.gitlab.com/$CI_PROJECT_PATH/format@$CI_COMMIT_SHA
```
include.component isn't working in the current state of gitlab-ci-local right ?

**Comment by ANGkeith** [comment]
> @ANGkeith
> 
> ```
> stages: [format, build, test]
> 
> include:
>   - component: example.gitlab.com/$CI_PROJECT_PATH/format@$CI_COMMIT_SHA
> ```
> 
> include.component isn't working in the current state of gitlab-ci-local right ?

yeah nope

**Pull request merged**
