### PR TITLE
sugestion to implement rules support in includes

### PR DESCRIPTION
**Pull request by gbenguria**
related with issue
add rules support to include #627

### CODE REVIEW

**Comment by firecow** [comment]
@gbenguria Can you remove that vscode file?

**Comment by firecow** [comment]
It would be best to include a test case under `tests/test-cases` @gbenguria

**Comment by gbenguria** [comment]
I am new to nodejs (and to github procedures xD ) and I have no knowledge on the testing framework and practices on this project. Therefore it will take a while to add some meaningful tests. Besides, there is a third issue that I will like to solve before addressing the testing of the added changes.

**Comment by gbenguria** [comment]
I am somehow new to this gihub pull request stuff, and I am thinking that maybe this should be added as draft ... but I do not find the way to put this in draft. So sorry for that.

**Comment by gbenguria** [comment]
converted to draft, I will come back as soon as I add some tests. That I should learn to implement...

**Comment by kouk** [comment]
@gbenguria do you want some help with this? I am interested in getting your changes into the mainline of this project, so could maybe contribute the tests.

**Comment by gbenguria** [comment]
I have upload my first test attemp so feel free to complain ;-)

**Review by firecow — APPROVED** [review]
lgtm

**Pull request merged**
