### PR TITLE
issue-717 (https://github.com/firecow/gitlab-ci-local/issues/717) 

### LINKED ISSUE #717: There is no support for cache:when
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
job:
  script:
    - exit 1
  cache:
    - when: always
      paths:
        - build
```

**Expected behavior**
Cache will be publish'ed, when job failed

**Host information**
Ubuntu
gitlab-ci-local 4.36.1

**Additional context**
I'll publish Pull Request soon

### PR DESCRIPTION
**Pull request by broneq**
Add support for cache:when (https://docs.gitlab.com/ee/ci/yaml/index.html#cachewhen)

closes #717

### CODE REVIEW

**Review by firecow — APPROVED** [review]
Epic job :smile:

**Comment by firecow** [comment]
@broneq You got yamllint findings :smile:

**Comment by broneq** [comment]
> @broneq You got yamllint findings 😄

fixed

**Comment by firecow** [comment]
@broneq Actions running, then I'll merge
Thanks for contributing.
You want a collaborator invite?

**Comment by broneq** [comment]
yes, with pleasure

**Comment by firecow** [comment]
> yes, with pleasure

Welcome aboard :smile:

**Pull request merged**
