### PR TITLE
Expand local includes that lives inside project-like includes.

### PR DESCRIPTION
**Pull request by firecow**

### CODE REVIEW

**Comment by bcouetil** [comment]
I'm testing it locally. Here is my first error : 

When the local(s) of the remote have a leading slash :

```
include:
  - local: "/.templates.gitlab-ci.yml"
  - local: "/.templates-gke.gitlab-ci.yml"
 ```
I have this error :
```
downloaded gitlab.cicd.my-compagny.com/group/remote/.local.gitlab-ci.yml in 1.27 s
remote: fatal: /.templates-gke.gitlab-ci.yml: '/.templates-gke.gitlab-ci.yml' is outside repository at '/home/git/repositories/@hashed/87/1c/871c39835ef093344f55dd14dab9ee5634fff2e2be7d8e656be8b.git/.'        
remote: git upload-archive: archiver died with error
fatal: sent error to the client: git upload-archive: archiver died with error
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```
If I remove the leading slash, it is OK. Removing it is easy, but finding what to do might be hard with the error text.

**Comment by bcouetil** [comment]
Other issue.

When stages are declared in the current file, or in the remote file, it is OK. But if they a declared in a local file of the remote file, they are not found :

```
downloaded gitlab.cicd.company.com/group/project/.local.gitlab-ci.yml in 1.26 s
downloaded gitlab.cicd.company.com/group/project/.templates-gke.gitlab-ci.yml in 1.21 s
downloaded gitlab.cicd.company.com/group/project/.templates.gitlab-ci.yml in 1.29 s
stage:🔍 Check 🔢 Calculate not found for version
```

**Comment by bcouetil** [comment]
Last error is perhaps something else : locals of remote might be cloned from default branch or master, env when `include:ref` is defined (so with `include:project+ref`)

I found out because an old version of a job in a local of a remote in running when I launch the pipeline.

**Comment by firecow** [comment]
@bcouetil Just to be sure.
Local includes inside project-like includes are also master even though the project-like's ref: might be something else?

**Comment by firecow** [comment]
@bcouetil I've removed the leading slash from file values, in projectFileRef includes. That should take care of the first problem.

**Comment by bcouetil** [comment]
> @bcouetil Just to be sure.
> Local includes inside project-like includes are refs: master even though the project-like's refs: might be something else?

Yes, that would explain both 2 errors.

**Comment by firecow** [comment]
@bcouetil I don't know about you, but that sounds like a bug made by gitlab, as it makes projectFileRef includes with local includes inside kindda dangerous.

Nonetheless, I shall make it similar in fasion.

**Comment by firecow** [comment]
@bcouetil Try it out now.

**Comment by bcouetil** [comment]
Screenshot from 2021-04-13 10-16-13

I did not explain myself well, that's why you understood that it should be master, and now I understand why you find it dangerous. This should not be forced to master, of course.


I have this parent :
**.gitlab-ci.yml**
```
include:
  - local: ".templates.gitlab-ci.yml"
```

and this child :

**.gitlab-ci.yml**
```
include:
    - project: group/parent
      file: .gitlab-ci.yml
      ref: my-branch
```

parent `.gitlab-ci.yml` is fetched with ref `my-branch`
parent `.templates.gitlab-ci.yml` should be fetched with ref `my-branch`, not master, and not the previous include[ref] of the local, but with the include[ref] of the parent project in the child.

Is it better explained ?

**Comment by firecow** [comment]
@bcouetil Take a look at the file changes now.

**Comment by bcouetil** [comment]
Seems good, cloning and testing right now...

**Comment by bcouetil** [comment]
Oh thank you @firecow it works :heart: 

When can we expect a release including this PR ? 🥰

**Review by bcouetil — APPROVED** [review]

**Comment by firecow** [comment]
@bcouetil In 10 minutes :smile:

**Pull request merged**
