### PR TITLE
Fixing that cache.paths can be undefined

### LINKED ISSUE #898: paths is always needed when using cache keyword
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
stages:
  - test
testjob:
  stage: test
  image: alpine:latest
  script:
    - echo "Hello World"
  cache:
    - key: $CI_COMMIT_REF_SLUG
```

**Unexpected behavior**
 ~/projects/github-bugreport  gitlab-ci-local testjob

Using fallback git commit data
Using fallback git remote data
**testjob cache[0].paths must be array**

**Expected behavior**
(By commenting out the cache part in .gitlab-ci.yml)
 ~/projects/github-bugreport  gitlab-ci-local testjob

Using fallback git commit data
Using fallback git remote data
parsing and downloads finished in 21 ms
testjob starting alpine:latest (test)
testjob copied to docker volumes in 489 ms
testjob $ echo "Hello World"
testjob > Hello World
testjob finished in 1.02 s

**Host information**
MacOS 13.3.1 
gitlab-ci-local 4.41.2

**Additional context**
It expects always an array for "paths". In many cases we don't need "paths" in Gitlab. 
"paths" in cache should be optional

### PR DESCRIPTION
**Pull request by firecow**
closes #898

### CODE REVIEW

**Comment by hverlin** [comment]
@firecow Do you still intend to merge this one? I can take it otherwise. 
I would like that it at least does not fail when using:
```
cache: {}
```
(or print a warning?)

I am not sure if you intended to create a different fix based on this [comment](https://github.com/firecow/gitlab-ci-local/issues/898#issuecomment-1584648472)
>

**Comment by firecow** [comment]
@hverlin Go ahead a finish it.
Don't recall whats needed to finish it.

**Comment by firecow** [comment]
I'm pretty sure a complete rewamp of the way caching works is needed.

**Comment by hverlin** [comment]
For now, this is just ignoring the cache if the path is empty.
I can work on a separate PR to get something like https://github.com/firecow/gitlab-ci-local/issues/898#issuecomment-1584642509 to work.

**Comment by firecow** [comment]
Should we close the issue then?

**Comment by hverlin** [comment]
Created another one: https://github.com/firecow/gitlab-ci-local/pull/1045

**Comment by hverlin** [comment]
@firecow I think you can merge this one, added a comment here:
https://github.com/firecow/gitlab-ci-local/issues/898#issuecomment-1822834356

**Review by firecow — COMMENTED** [review]
Looks good 👍

**Comment by firecow** [comment]
@hverlin You have to approve it, since its my PR

**Review by hverlin — APPROVED** [review]

**Pull request merged**
