### PR TITLE
Use .replaceAll() instead of .replace() for aliases for containers wi…

### LINKED ISSUE #649: Service Container uses incorrect alias for health check, causing timeout
This is a followup to #639. That one now works correctly, but I run into the following issue

**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
hello-world:
  services:
    - ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
  script:
    - echo "Hello World"
```

**Expected behavior**
Service container health check runs correctly and does not timeout

**Host information**
Ubuntu
gitlab-ci-local 4.35.0

**Additional context**
Using this simple example, the health check always times out. This is because an alias with a `/` is used in the healthcheck container as a hostname, which can't resolve. The cause is that the container name has more than one slash. These are the logs:

```
wait-for-it.sh: waiting 30 seconds for ghcr.io-peterbbeu/gitlab-ci-local-testcase:80
wait-for-it.sh: timeout occurred after waiting 30 seconds for ghcr.io-peterbbeu/gitlab-ci-local-testcase:80
```

This is the `gitlab-ci-local` log:
```
parsing and downloads finished in 59 ms
hello-world starting shell (test)
hello-world started service image: ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest with aliases: ghcr.io-peterbbeu/gitlab-ci-local-testcase, ghcr.io__peterbbeu/gitlab-ci-local-testcase in 558 ms
hello-world > still running...
hello-world > still running...
hello-world > still running...
hello-world service image: ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest healthcheck failed: ghcr.io-peterbbeu/gitlab-ci-local-testcase:80
hello-world see (/home/peter/projects/gitlab-ci-local-testcase/.gitlab-ci-local/services-output/hello-world/ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest-0.log)
hello-world service image: ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest healthcheck passed in 31 s
hello-world $ docker pull ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
hello-world > latest: Pulling from peterbbeu/gitlab-ci-local-testcase
hello-world > Digest: sha256:fde0b84df1a23758596760fd8ca252d791c12e4dce1fc9432ca3b293d388a4d9
hello-world > Status: Image is up to date for ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
hello-world > ghcr.io/peterbbeu/gitlab-ci-local-testcase:latest
hello-world $ echo "Hello World"
hello-world > Hello World
hello-world finished in 32 s
```

I have created a PR with what I think should solve this: https://github.com/firecow/gitlab-ci-local/pull/648

Also, i've tried manually adding an `alias: foobar` in the service container, however the first alias will always be used:

https://github.com/firecow/gitlab-ci-local/blob/master/src/job.ts#L1020
```typescript
            const spawnCmd = ["docker", "run", "--rm", "--network", `gitlab-ci-local-${this.jobId}`, "willwill/wait-for-it", `${aliases[0]}:${portNum}`, "-t", "30"];
```

### PR DESCRIPTION
**Pull request by peterbbeu**
Fixes aliases with multiple slashes so the healthcheck container can connect correctly closes #649

### CODE REVIEW

**Comment by firecow** [comment]
Can you add a simple test to avoid a potential regression of this issue?

**Comment by pedroterzero** [comment]
> Can you add a simple test to avoid a potential regression of this issue?

I'll have a look hopefully tomorrow or early next week!

**Comment by peterbbeu** [comment]
> Can you add a simple test to avoid a potential regression of this issue?

Apologies, it took me a while, but I hope this test is satisfactory.

**Review by firecow — APPROVED** [review]
Looks good to me, thanks for the contribution.

**Pull request merged**
