### PR TITLE
feat: enable json schema validation by default

### PR DESCRIPTION
**Pull request by ANGkeith**
https://github.com/firecow/gitlab-ci-local/pull/1167#discussion_r1558871053

Whenever we're ready

### CODE REVIEW

**Comment by firecow** [comment]
Create a 5.x.x branch, and point this PR towards that.

That way we can manage all the breaking changes in the 5.x.x branch.

**Comment by ANGkeith** [comment]
hmm, why do you consider this a breaking change though, i see it more as a feature

**Comment by firecow** [comment]
@ANGkeith Well, if it doesn't break anything, I'm open to just merge it to master, and include it in the upcoming release.

Let me test it on our 50ish projects :smile:

**Comment by ANGkeith** [comment]
> @ANGkeith Well, if it doesn't break anything, I'm open to just merge it to master, and include it in the upcoming release.
> 
> Let me test it on our 50ish projects 😄

nice, let me know how it goes


however, there's some edge case as per what @PigeonF  discovered in https://github.com/firecow/gitlab-ci-local/pull/1229#issue-2309870744 . 

It appears that GitLab.com is still able to process the .gitlab-ci.yml file even when it's provided with an invalid JSON schema.

**Comment by firecow** [comment]
@ANGkeith My 50ish projects had no problems, point this to master, and we will release in next minor version

If gitlab doesn't uphold their our json schema, that's their problem :smile:

**Comment by firecow** [comment]
@ANGkeith Conflicts...
I'll publish new version once this is in master.

**Review by firecow — APPROVED** [review]

**Pull request merged**
