### PR TITLE
Add option "--timestamps" to show timestamps and job duration  in the logs

### LINKED ISSUE #846: Show timestamp and current running time in the logs?
### Discussed in https://github.com/firecow/gitlab-ci-local/discussions/844

<div type='discussions-op-text'>

<sup>Originally posted by **hverlin** May  4, 2023</sup>
Hi, I was wondering if you would be open adding an option to show the current time + runtime in the logs.
This is really useful for long-running jobs to get a better idea of how much time things have taken. Not all processes output the timestamps, unfortunately.

I could create a cleaner patch but for now, I just added a very simple change like this.
```ts
    get chalkJobName () { // rename
        const currentTime = new Date().toISOString().split("T")[1].split(".")[0];
        const runningFor = prettyHrtime(process.hrtime(this.startTime));

        // [16:33:19 (1.37 min)] my-job     > hello world
        return chalk`[${currentTime} (${runningFor})] {blueBright ${this.name.padEnd(this.jobNamePad)}}`;
    }
```

Let me know if you are interested in supporting it as an official option

(note that GitLab CI does not support this feature yet… https://gitlab.com/gitlab-org/gitlab/-/issues/202293)</div>

----

> I have thought about adding time to each line, but decided against it, because it make the lines quite long.
> Having a --timestamps boolean cli option would be preferable, and would definently reach master +1

### PR DESCRIPTION
**Pull request by hverlin**
Resolves #846

Example output

output with timestamps

```shell
❯ gcl --timestamps
parsing and downloads finished in 34 ms
[15:17:52 1.15 ms] build-job  starting shell (build)
[15:17:52 6.44 ms] build-job  $ sleep 1
[15:17:53  1.01 s] build-job  $ echo 'test done'
[15:17:53  1.01 s] build-job  > test done
[15:17:53  1.01 s] build-job  finished in 1.01 s
[15:17:53  838 μs] failed-job starting shell (.post)
[15:17:53 6.34 ms] failed-job $ exit 1
[15:17:53 6.73 ms] failed-job finished in 6.73 ms  FAIL 1

 PASS  [ 1.01 s] build-job
 FAIL  [6.73 ms] failed-job
pipeline finished in 1.11 s
```

### CODE REVIEW

**Review by firecow — APPROVED** [review]
Looks good to me, to master it goes.
It has some conflicts with master branch, though @hverlin

**Comment by hverlin** [comment]
Should be good now :+1:

**Comment by firecow** [comment]
I'll release tomorrow, we have plenty features and patches to justify a releaae 👍

**Comment by firecow** [comment]
If you got time @hverlin, I could use some eyes on https://github.com/firecow/gitlab-ci-local/pull/838 and https://github.com/firecow/gitlab-ci-local/pull/837 before we release.

**Pull request merged**
