### PR TITLE
Endreport/output formatter

### PR DESCRIPTION
**Pull request by ZobairQ**
This PR changes the way output of the endreport is presented. 
The endreport output is modified to have following:
- A color coded table 
- The status can be PASS, WARN and FAIL 
- The stage of each job
- The script type, e.g. whether it's a prescript or afterscript job

### CODE REVIEW

**Review by firecow — COMMENTED** [review]
image
Background color "takeover" doesn't play well with my terminal.
I think it takes up too much space, and I find it weird that the jobname colums aren't aligned.


image
Some of the text is barely visible in another terminal emulator i tried.

**Review by firecow — COMMENTED** [review]
https://github.com/firecow/gitlab-ci-local/pull/109/files#diff-40e63732067d814128de080bb2ad014a64b1fbd92410aac4a0c9e30e4cf9041bR140
preScripts.never array isn't used anymore.

**Comment by bcouetil** [comment]
It looks promising, but yeah, the horizontal lines are not necessary.

**Comment by firecow** [comment]
image
image

Something similar without the table lines. Just for illustrating how it will look without the lines n' such.

**Comment by bcouetil** [comment]
Perfect

**Comment by ZobairQ** [comment]
I like the last one with headers.. 
The problem I was trying to solve is when the users have a white background in their terminal. The contrast gets pretty shitty and lighter font colors cannot be read properly.

**Review by bcouetil — APPROVED** [review]
LGTM, merge if and when ready :smile:

**Comment by firecow** [comment]
Closing this PR in favour of https://github.com/firecow/gitlab-ci-local/pull/137

**Pull request closed without merging**
