### PR TITLE
Fix Docker CP bug

### PR DESCRIPTION
**Pull request by firecow**

### CODE REVIEW

**Comment by bcouetil** [comment]
Thanks, I'm trying that and report ASAP

**Comment by bcouetil** [comment]
Still keeping that in mind.

Note : I've spoken of this tool to my 500+ devs IT company, hence the bump in stars :blush:

**Comment by bcouetil** [comment]
I run into the bug at least once a day. Next week I'll switch to the fix, and if it does not happen anymore in a few days, I'll consider this fixed !

**Comment by firecow** [comment]
@bcouetil Yeah, try it out for a week.
I must admit, that this "fix" is pure speculation on my behalf...
I find it extremely weird that the docker create command would exit, before the containers is actually ready. 
But then again, who knows :smile:

**Comment by bcouetil** [comment]
Maybe this can help the case : 

Screenshot from 2021-04-17 22-23-29

There can be no containerId in output. And that would explain the error mentioned in the issue : `must specify at least one container source`

Maybe launching multiple containers at the same time make some output with nothing and others with 2 containers ? Should we queue containers creation ?

**Comment by firecow** [comment]
Aaaa.... Nice...
I'm setting up a 1000 docker create example to be able to reproduce this more consistently @bcouetil 😃

**Comment by firecow** [comment]
image

image

I can reproduce every single time.
It looks like a bug with docker create if you ask me @bcouetil

**Comment by firecow** [comment]
image

This bash script doesn't leave any "empty" container id's

@bcouetil Its a nodejs (Utils.spawn) problem, somehow...

**Comment by bcouetil** [comment]
You could just spawn again on empty output, easy workaround ?

**Comment by firecow** [comment]
@bcouetil My current setTimeout(func, 10) "hack" works with 1000x docker create.
Apparently the stdout and stderr's can be slashed by nodejs somehow, if enough child processes are spawned.

**Comment by firecow** [comment]
@bcouetil I'm merging this into master, if you approve.

**Review by bcouetil — APPROVED** [review]
Wonderful ! Approved

**Pull request merged**
