### PR TITLE
feat: Adding --umask (default true) option

### LINKED ISSUE #671: --disable-umask cli option
**Is your feature request related to a problem? Please describe.**
gitlab-ci-local seems to always do `docker create -u 0:0 ..`

This causes problems with file ownership and running applications/testing

**Describe the solution you'd like**
`docker create ...` without -u

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by alexander-matthiesen**
closes #671

### CODE REVIEW

**Comment by alexander-matthiesen** [comment]
> We cannot make this option default to true, when gitlab's default is false.

So currently the `--umask` activates the `--user 0:0` and `--umask` is set to true by default. 
Do I have a logic issue in my head or do I misunderstand the `umask` setting?

If we set `--umask` default to `false`, the `--user 0:0` would not be added and this would be a breaking change to the current setup.

**Comment by firecow** [comment]
> > We cannot make this option default to true, when gitlab's default is false.
> 
> So currently the `--umask` activates the `--user 0:0` and `--umask` is set to true by default. 
> Do I have a logic issue in my head or do I misunderstand the `umask` setting?
> 
> If we set `--umask` default to `false`, the `--user 0:0` would not be added and this would be a breaking change to the current setup.

Let me look at the code again... Maybe I got it wrong.

**Comment by firecow** [comment]
> > > We cannot make this option default to true, when gitlab's default is false.
> > 
> > So currently the `--umask` activates the `--user 0:0` and `--umask` is set to true by default. 
> > Do I have a logic issue in my head or do I misunderstand the `umask` setting?
> > 
> > If we set `--umask` default to `false`, the `--user 0:0` would not be added and this would be a breaking change to the current setup.
> 
> Let me look at the code again... Maybe I got it wrong.

Yes i did. It has to be true of course 🤟

**Review by firecow — APPROVED** [review]
lgtm

**Pull request merged**
