### PR TITLE
Auto generate .gitlab-ci-local/.gitignore file If .gitignore file isn't git add'ed right away, make sure .gitlab-ci-local is excluded from rsync

### PR DESCRIPTION
**Pull request by firecow**
@bcouetil @JoyceBabu 

I was able to reproduce, when ever .gitlab-ci-local/.gitignore wasn't manually git add'ed, the recursive behavior occurs.

### CODE REVIEW

**Comment by bcouetil** [comment]
I came to say that I easily reproduced also :smile:

**Comment by bcouetil** [comment]
Tested this branch, working like a charm :muscle:

**Comment by firecow** [comment]
@bcouetil Approve, lets get it right in :smile:

**Comment by JoyceBabu** [comment]
@firecow Great. Usually when you add a gitignore file with content '*`, you won't be committing the file (unless you want to create an empty directory). So, the PR is useful. But now I think it is safe to exclude the entire `.gitlab-ci-local` directory, not just `.gitlab-ci-local/builds/${target}`.

**Review by bcouetil — APPROVED** [review]
tested, LGTM

**Pull request merged**
