### PR TITLE
Rules not validated correctly

### PR DESCRIPTION
**Pull request by alexander-matthiesen**
Somehow the rules are not getting correctly validated when having a variable determine the `when:` status:

```
test-job:
  stage: build
  script:
    - echo "$TEST!"
  rules:
    - if: $TEST == "true"
      when: on_success
    - if: $TEST != "true"
      when: manual
```

### CODE REVIEW

**Comment by firecow** [comment]
@alexander-matthiesen Have you tested this with latest master?

**Comment by alexander-matthiesen** [comment]
@firecow I have written two tests to show the issue. Maybe you can check them. They should be up to date with the latest master.

**Comment by firecow** [comment]
🤟

**Comment by firecow** [comment]
image

image

I don't see the bug here. Can you elaborate, please?

**Comment by firecow** [comment]
https://github.com/firecow/gitlab-ci-local/pull/711/commits/040b8f023bbf0dd323e95c9dfe6cfacecc1734de

This commit suggest you are seeing ghosts :smile:

**Pull request closed without merging**
