### PR TITLE
Remove the pipeline id from the .gitlab-ci-local/artifacts folder

### PR DESCRIPTION
**Pull request by firecow**

### CODE REVIEW

**Comment by bcouetil** [comment]
Did not see code yet, but we should clean the folder at pipeline start, to not have old artifacts pretending to be for the new pipeline.

**Comment by firecow** [comment]
@bcouetil Only on pipelines and "needs" pipelines right ?

**Comment by bcouetil** [comment]
yes I think you are right, to have best behavior.

**Comment by firecow** [comment]
@bcouetil Done

**Review by bcouetil — APPROVED** [review]
LGTM

**Pull request merged**
