### PR TITLE
Support artifacts with globstar pattern

### PR DESCRIPTION
**Pull request by firecow**

### CODE REVIEW

**Comment by bcouetil** [comment]
You're so fast :pray: 

I'm testing it locally...

**Comment by bcouetil** [comment]
Does not seem to work on my side, do I miss something obvious ?

Screenshot from 2021-05-05 12-13-57

**Comment by firecow** [comment]
> Does not seem to work on my side, do I miss something obvious ?
> 
> Screenshot from 2021-05-05 12-13-57

Yes, I added a failing test.
I haven't actually implemented anything, yet 😃

**Comment by bcouetil** [comment]
Okay good, I've been misguided by the approval request :blush:

**Comment by firecow** [comment]
> Okay good, I've been misguided by the approval request 😊

I think I've gotten it figured out soon. Sorry, for the ping 😃

**Comment by firecow** [comment]
@bcouetil We are out of Draft

**Review by bcouetil — APPROVED** [review]
Tested, working, thanks !

Code looks OK too.

**Pull request merged**
