### PR TITLE
Flatten lists and fix !reference recursiveness

### LINKED ISSUE #306: !reference breaks if the "parent" isn't defined first
**Minimal .gitlab-ci.yml illustrating the issue**
Does not work:
```yml
---
parent:
  script:
    - !reference [ .child, script ]

.child:
  script:
    - echo 'Mads'
    - !reference [ .grandchild, script ]

.grandchild:
  script:
    - echo 'Jon'
```

Works:
```yml
---
.grandchild:
  script:
    - echo 'Jon'

.child:
  script:
    - echo 'Mads'
    - !reference [ .grandchild, script ]

parent:
  script:
    - !reference [ .child, script ]
```

**Output**
```
TypeError: script.split is not a function
    at /snapshot/gitlab-ci-local/src/job.ts:399:34
    at Array.forEach (<anonymous>)
    at Job.generateScriptCommands (/snapshot/gitlab-ci-local/src/job.ts:397:17)
    at Job.execScripts (/snapshot/gitlab-ci-local/src/job.ts:549:21)
    at Job.start (/snapshot/gitlab-ci-local/src/job.ts:290:36)
```

**Expected behavior**
The `parent` job should execute.

**Host information**
Ubuntu 20.04.2 LTS
gitlab-ci-local 4.26.0

**Additional context**

### LINKED ISSUE #426: Error with rules and !reference
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
.pipeline_rules:
  rules:
    - if: $GITLAB_CI == 'false'
      when: manual
foo:
  rules:
    - if: $UPSTREAM_CI_COMMIT_BRANCH == 'asdfqwerwetysdfv'
      when: on_success
    - !reference [.pipeline_rules, rules]
    - when: never
  script:
    - echo 'foobar'
```
Output from `gitlab-ci-local --preview`:
```yml
  rules:
    - if: $UPSTREAM_CI_COMMIT_BRANCH == 'asdfqwerwetysdfv'
      when: on_success
    - - if: $GITLAB_CI == 'false'
        when: manual
    - when: never
```
Note the nested list. 

**Expected behavior**
"foo" job should be "manual", not "on_success".  I was expecting the list to be flattened.
```yml
  rules:
    - if: $UPSTREAM_CI_COMMIT_BRANCH == 'asdfqwerwetysdfv'
      when: on_success
    - if: $GITLAB_CI == 'false'
      when: manual
    - when: never
```

**Host information**
macOS Monterey 12.3.1
gitlab-ci-local 4.30.1

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by firecow**
closes #306 
closes #426

### CODE REVIEW

**Comment by atc-cegodk** [comment]
`npm run build` fails on my machine.

`git show-ref flatten-lists`  
> 8b98aa51fb448d742ba40dc6590af13295fb3793 refs/heads/flatten-lists
> 8b98aa51fb448d742ba40dc6590af13295fb3793 refs/remotes/origin/flatten-lists

`npm install` works.
Output from `npm run build`: https://gist.github.com/atc-cegodk/819aea27ed6854193a693cf653338982

My machine:  
macOS 12.3 Monterey (x86_64 Intel CPU)
`node --version ; npm --version`  
> v16.15.0
> 8.5.5

**Comment by firecow** [comment]
> `npm run build` fails on my machine.
> 
> `git show-ref flatten-lists`
> 
> > [8b98aa5](https://github.com/firecow/gitlab-ci-local/commit/8b98aa51fb448d742ba40dc6590af13295fb3793) refs/heads/flatten-lists
> > [8b98aa5](https://github.com/firecow/gitlab-ci-local/commit/8b98aa51fb448d742ba40dc6590af13295fb3793) refs/remotes/origin/flatten-lists
> 
> `npm install` works. Output from `npm run build`: https://gist.github.com/atc-cegodk/819aea27ed6854193a693cf653338982
> 
> My machine: macOS 12.3 Monterey (x86_64 Intel CPU) `node --version ; npm --version`
> 
> > v16.15.0
> > 8.5.5

Hmm... Works on my machine :laughing: 
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npm install && npm run build

added 608 packages, and changed 1 package in 3s

> gitlab-ci-local@4.30.1 build
> rm -f src/*.js src/*.d.ts && tsc

```shell
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ git clean -fdx -e .idea
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npm --version
8.5.5
mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ node --version
v16.15.0
```

**Comment by atc-cegodk** [comment]
> > `npm run build` fails on my machine.
> > `git show-ref flatten-lists`
> > > [8b98aa5](https://github.com/firecow/gitlab-ci-local/commit/8b98aa51fb448d742ba40dc6590af13295fb3793) refs/heads/flatten-lists
> > > [8b98aa5](https://github.com/firecow/gitlab-ci-local/commit/8b98aa51fb448d742ba40dc6590af13295fb3793) refs/remotes/origin/flatten-lists
> > 
> > 
> > `npm install` works. Output from `npm run build`: https://gist.github.com/atc-cegodk/819aea27ed6854193a693cf653338982
> > My machine: macOS 12.3 Monterey (x86_64 Intel CPU) `node --version ; npm --version`
> > > v16.15.0
> > > 8.5.5
> 
> Hmm... Works on my machine 😆 mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npm install && npm run build
> 
> added 608 packages, and changed 1 package in 3s
> 
> > gitlab-ci-local@4.30.1 build
> > rm -f src/_.js src/_.d.ts && tsc
> 
> ```shell
> mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ git clean -fdx -e .idea
> mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npm --version
> 8.5.5
> mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ node --version
> v16.15.0
> mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npx tsc
> ```

I think that I first ran `npm install` with the newest nodejs (v18.0), then downgraded to the current LTS (v16.15).

after a `git clean -fdx` and retrying, it works 🤷  Something funky on my machine. Ignore this thread 😅

**Comment by firecow** [comment]
> > > `npm run build` fails on my machine.
> > > `git show-ref flatten-lists`
> > > > [8b98aa5](https://github.com/firecow/gitlab-ci-local/commit/8b98aa51fb448d742ba40dc6590af13295fb3793) refs/heads/flatten-lists
> > > > [8b98aa5](https://github.com/firecow/gitlab-ci-local/commit/8b98aa51fb448d742ba40dc6590af13295fb3793) refs/remotes/origin/flatten-lists
> > > 
> > > 
> > > `npm install` works. Output from `npm run build`: https://gist.github.com/atc-cegodk/819aea27ed6854193a693cf653338982
> > > My machine: macOS 12.3 Monterey (x86_64 Intel CPU) `node --version ; npm --version`
> > > > v16.15.0
> > > > 8.5.5
> > 
> > 
> > Hmm... Works on my machine laughing mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npm install && npm run build
> > added 608 packages, and changed 1 package in 3s
> > > gitlab-ci-local@4.30.1 build
> > > rm -f src/_.js src/_.d.ts && tsc
> > 
> > 
> > ```shell
> > mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ git clean -fdx -e .idea
> > mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npm --version
> > 8.5.5
> > mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ node --version
> > v16.15.0
> > mjn@mjn-laptop:~/workspace/firecow-gitlab-ci-local$ npx tsc
> > ```
> 
> I think that I first ran `npm install` with the newest nodejs (v18.0), then downgraded to the current LTS (v16.15).
> 
> after a `git clean -fdx` and retrying, it works shrug Something funky on my machine. Ignore this thread sweat_smile

I'm added the two missing types to package.json dev dependencies

**Review by atli-c — APPROVED** [review]
LGTM

**Comment by bcouetil** [comment]
Thank you for this 😊

**Pull request merged**
