### PR TITLE
fix: wrong line number in stack trace

### PR DESCRIPTION
**Pull request by ANGkeith**
npm uninstall ts-node source-map-support @types/source-map-support
npm install --save-dev tsx

# Issue
Using the following 
```yaml
# .gitlab-ci.yaml
---
job:
  image: test-err
  script:
    - echo 1
```

image
The stack trace returns the wrong line number. 

which is possibly related to https://www.github.com/TypeStrong/ts-node/issues/2053, thus replacing `ts-node` with `tsx`

### CODE REVIEW

**Review by firecow — APPROVED** [review]

**Comment by firecow** [comment]
merge with master please @ANGkeith

**Comment by firecow** [comment]
@ANGkeith We need to ensure that stack traces in the pkg binaries still works, when you remove the sourcemap package.

**Comment by ANGkeith** [comment]
opps, forgot about that..

but do we really need sourcemap for the binary ? 

i thought sourcemap is more for dev/debugging

**Comment by ANGkeith** [comment]
anyways, 

> @ANGkeith We need to ensure that stack traces in the pkg binaries still works, when you remove the sourcemap package.

should be fixed already

**Comment by firecow** [comment]
@ANGkeith We don't have any security concerns going on in this tool, so I can't think of a reason why we would want to exclude such epic piece of debug information, when users make bug reports.

**Pull request merged**
