### PR TITLE
refactor: rewrite unit-test to make it less dependent the stdout/stderr length

### PR DESCRIPTION
**Pull request by ANGkeith**

### CODE REVIEW

**Comment by firecow** [comment]
@ANGkeith I was just about to ask you if you still wanted this in master :smile:

**Comment by firecow** [comment]
@ANGkeith Do you have something important in the pipeline in the next couple of days?
If not, I'll prepare the 4.48.0 release

**Comment by ANGkeith** [comment]
> @ANGkeith I was just about to ask you if you still wanted this in master 😄

Haha it was already merged in #1186

Was thinking about splitting the MRs to make it easier to review

**Comment by firecow** [comment]
> > @ANGkeith I was just about to ask you if you still wanted this in master 😄
> 
> Haha it was already merged in #1186
> 
> Was thinking about splitting the MRs to make it easier to review

Nah, your PR's are way easy to review :smile:

**Comment by ANGkeith** [comment]
> @ANGkeith Do you have something important in the pipeline in the next couple of days? If not, I'll prepare the 4.48.0 release

yup please go ahead, thankss

**Pull request closed without merging**
