### PR TITLE
Add serviceHealthCheck

### PR DESCRIPTION
**Pull request by HeWhoWas**
This PR is an amateur attempt at adding a generic service healthCheck function. It works by:

1. Using `docker inspect <service_name>` to identify a list of ports exposed by the image.
2. Runs an instance of [willwill/wait-for-it](https://hub.docker.com/r/willwill/wait-for-it) in docker, that wait for up to 30 seconds for the service to become available.

This logic was based on a small blurb on the [GitLab Services Page](https://docs.gitlab.com/ee/ci/services/#how-the-health-check-of-services-works)

> To make sure this works, the runner:
>
>    1. Checks which ports are exposed from the container by default.
>    2. Starts a special container that waits for these ports to be accessible. 

I'm not a JS developer, and this is literally the first time I've used TS. If I've done anything egregious, happy to change it.

Should fix https://github.com/firecow/gitlab-ci-local/issues/301

### CODE REVIEW

**Comment by firecow** [comment]
@HeWhoWas All in all good work... 

Lets use https://www.npmjs.com/package/wait-port instead of "eating" the overhead of starting a container just to check if a TCP port is responding.

**Comment by HeWhoWas** [comment]
I originally intended to use the `net` package in order to introduce as few dependencies as possible, but it didn't work due to the fact that the service name only resolves within the same docker network. If we want to avoid calling out to `docker run` then I think the only option would be to expose the docker DNS server to the host and query it directly.

**Comment by firecow** [comment]
@HeWhoWas Thats right, didn't think about docker network dns name... My bad :smile:

**Review by firecow — APPROVED** [review]
lgtm

**Comment by HeWhoWas** [comment]
No problem, thanks!

**Pull request merged**
