### PR TITLE
Fix #1154

### LINKED ISSUE #1154: gitlab-ci-local fails to parse to-be-continous templates
**Minimal .gitlab-ci.yml illustrating the issue**
```yml
---
include:
  - remote: "https://gitlab.com/to-be-continuous/docker/raw/5.8.1/templates/gitlab-ci-docker.yml"
```

**Expected behavior**
The included file is downloaded and parsed correctly.

**Host information**
macOS 14
gitlab-ci-local 4.47.0

**Containerd binary**
Docker via Colima.

**Additional context**
The included file is using components, which gitlab-ci-local is now able to handle, thanks to #1115.

It now has two problems: 

- You cannot use interpolation of input variables containing an hyphen like [this](https://gitlab.com/to-be-continuous/docker/-/blob/5.8.1/templates/gitlab-ci-docker.yml#L228) because the [regexp](https://github.com/firecow/gitlab-ci-local/blob/4.47.0/src/parser.ts#L289) doesn't allow them
- Interpolation of variables with values containing [escapes](https://gitlab.com/to-be-continuous/docker/-/blob/5.8.1/templates/gitlab-ci-docker.yml#L72) produce invalid JSON output which make the JSON parsing fail [here](https://github.com/firecow/gitlab-ci-local/blob/4.47.0/src/parser.ts#L307)

### PR DESCRIPTION
**Pull request by aveyrenc**
Attempt to fix issues reported in #1154

### CODE REVIEW

**Comment by firecow** [comment]
@aveyrenc Can you write a test please?

**Comment by aveyrenc** [comment]
> @aveyrenc Can you write a test please?

Sure, I just added the tests

**Comment by firecow** [comment]
@aveyrenc eslint failed

**Comment by aveyrenc** [comment]
Just fixed eslint

**Review by firecow — APPROVED** [review]

**Pull request merged**
