### PR TITLE
feat(554): supporting exists feature in rules

### PR DESCRIPTION
**Pull request by alexander-matthiesen**
#554

### CODE REVIEW

**Comment by alexander-matthiesen** [comment]
I've noticed that the github action "build/jest" is always checking out master. Therefore the added tests for rules exists are not taken please in the "pipeline". It might be confusing since every action is green and might suggest a working test testsetup.

**Comment by firecow** [comment]
@alexander-matthiesen
Can you spot my mistake in .github/workflows?

**Comment by alexander-matthiesen** [comment]
I've tried a bit but unfortunately I haven't that much experience with github workflows. I'm more of an expert with GitLab CI/CD (thats also why I'm here. :D 

I will have a look. Maybe it is working better now when I can create a branch in this repo here instead of having a fork.

**Comment by firecow** [comment]
Hehe, me too 😁I'll read up, and try some things, then you can pull master and see if that helps 🤟

**Comment by alexander-matthiesen** [comment]
Actually I will close this PR and create a new one based on a branch in this repository. 
I really don't like the "forking" stuff.
Follow up PR will come asap.

**Pull request closed without merging**
