### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AmineDjeghri**

### CODE REVIEW

**Comment by ANGkeith** [comment]
it's kinda already documented. have you seen this? 
https://github.com/firecow/gitlab-ci-local?tab=readme-ov-file#project-file-variables

how some re-arrangement ? do you think this will be better ? 
image

**Comment by AmineDjeghri** [comment]
The only thing that bothers me (but it might be only me) is that we have a section for dotenv at the beginning. So I don't know if the users will see the second section .

Thank you again for this feature !

**Comment by ANGkeith** [comment]
> The only thing that bothers me (but it might be only me) is that we have a section for dotenv at the beginning. 

yeah.. i got confused by it initially as well haha..

**Review by firecow — APPROVED** [review]

**Comment by firecow** [comment]
@AmineDjeghri Please merge master into your branch

**Comment by AmineDjeghri** [comment]
@firecow Done !

**Comment by firecow** [comment]
@AmineDjeghri Can you merge with origin/master again please

**Comment by firecow** [comment]
Reopen if you get back to this

**Comment by AmineDjeghri** [comment]
I will try to work on it this week

**Pull request closed without merging**
