### PR TITLE
Fixing my linting issues from early, plus some test improvements

### PR DESCRIPTION
**Pull request by aepfli**
I fixed the linting issues i created.

Additionally, i adapted the git remote tests and also added a minor fix to it, based on the open PR (i forgot to remove the change, when testing, thats why it is part of this PR sorry for that.)

Additionally i tried to improve readability within the rules tests - with `test.each` maybe this is something we want to add, maybe not, i can definitely remove it, if not needed.

### CODE REVIEW

**Comment by firecow** [comment]
I'll take care of linting while i'm fixing other tests that fails in master. Closing this. @aepfli Thanks though

**Comment by aepfli** [comment]
:+1: i am fine with that, i still do not like it to leave a mess for others to fix.

sidequestion, if i prepare another workflow for juts merge requests, without sonarcloud, and just leveraging linting, testing etc - would this be fine for you? - so to have at least a bear minimum of verification for the prs?

**Comment by aepfli** [comment]
and can you shortly take a look at the `rules.test.ts` within this pull request - if this proposed changed of structure is something feasible for you or not. i can try to leverage this approach for more tests to reduce the boilerplate ;)

**Comment by firecow** [comment]
forEach based approach is fine by me

I'm pretty indifferent just as long as the different cases are tested.

I've sent you a collaborator invite, you can utililize the github actions then.

@aepfli

**Pull request closed without merging**
