### PR TITLE
Handle multiple file includes from same project

### PR DESCRIPTION
**Pull request by Thracky**
This is a relatively simple and somewhat naive fix for #330 that assumes if `value["file"]` isn't a string that it must be an Array and iterates accordingly.

### CODE REVIEW

**Comment by firecow** [comment]
@Thracky Many many thanks for your first contribution, much appreciated :partying_face: 
You need to fix the eslint issues https://github.com/firecow/gitlab-ci-local/runs/4474538041?check_suite_focus=true
Also could you add a test case illustrating that `file:` being an array results in a successful run?

**Comment by firecow** [comment]
@Thracky Fuck me, sorry man :smile: 
Yamllint is being a bad boy now https://github.com/firecow/gitlab-ci-local/runs/4474808304?check_suite_focus=true

**Comment by Thracky** [comment]
> @Thracky Many many thanks for your first contribution, much appreciated 🥳 You need to fix the eslint issues https://github.com/firecow/gitlab-ci-local/runs/4474538041?check_suite_focus=true Also could you add a test case illustrating that `file:` being an array results in a successful run?
> 
> Perhaps just make a small change in `tests/test-cases/include-project-file-ref/.gitlab-ci.yml`

On it, just need to fiddle with the test case as I've been working with bracket-free YAML and messed up the syntax.

**Comment by firecow** [comment]
> > @Thracky Many many thanks for your first contribution, much appreciated partying_face You need to fix the eslint issues https://github.com/firecow/gitlab-ci-local/runs/4474538041?check_suite_focus=true Also could you add a test case illustrating that `file:` being an array results in a successful run?
> > Perhaps just make a small change in `tests/test-cases/include-project-file-ref/.gitlab-ci.yml`
> 
> On it, just need to fiddle with the test case as I've been working with bracket-free YAML and messed up the syntax.

Epic :smile:

**Review by firecow — APPROVED** [review]
lgtm thanks @Thracky

**Pull request merged**
